/**
 * A namespace containing constants generated by the Meson build script.
 *
 * THIS FILE IS AUTOMATICALLY MODIFIED BY MESON.
 * DO NOT MANUALLY CHANGE ANY OF THE VARIABLES.
 */
namespace Constants {
	public const string INDICATOR_NAME          = @INDICATOR_NAME@;
    public const string DATA_DIR                = @DATA_DIR@;
    public const string GETTEXT_PACKAGE         = @GETTEXT_PACKAGE@;

    public const string WINGPANEL_INDICATOR_DIR = @WINGPANEL_INDICATOR_DIR@;
    public const string AYATANA_INDICATOR_DIR   = @AYATANA_INDICATOR_DIR@;
}
